### ISSUE TITLE
After upgrade to 2.23.2 SMS sending doesn't work

### ISSUE THREAD

**Issue by p53** [privacyidea/privacyidea#1300]
# What did you try to do?
upgrade from 2.22 to 2.23.2

what we do:
request with user from ldap user store to /validate/check:

```
curl -s -G  --data-urlencode "user=someuser" --data-urlencode 'pass=somepass' "https://10.21.14.18/validate/check"

{"jsonrpc": "2.0", "signature": "201049308401531134466178065189764571120937256495599666440236272523262083204662134655387268637499363188487990132679731070653758739645758790604682520139088908523530166515196551385947250801353401744023649917
61335985015785180973348712642884481634456623589860941400203299037026267601077802940029462910865089468985755023177633327339270482067992148997967215436282706193767404151694564368848775892562148180428656143686034291765257208083046673602651163540338616213706951511582975868905374570955954941580904582151397903198452403577024861800750169502719282326113884454626836528094982171139409841463332640108623768324753050274757", "detail": {"message": "The user authenticated against his 
userstore according to policy 'some_authentication'.", "threadid": 140115258906368}, "versionnumber": "2.22", "version": "privacyIDEA 2.22", "result": {"status": true, "value": true}, "time": 1541424060.54929, "id": 1
}
```

, we have policy which creates new SMS token when user from ldap doesn't have token assigned yet, SMS should be (and in 2.22 it is) in form +031058788 when clicking on SMS token detail, in 2.23 it is in form [+031058788] and PI tries to send SMS to this invalid number so SMS sending fails

we don't use dynamic with SMS token

**Comment by cornelinux** [comment]
I guess you have an event handler, that creates a token? Not an SMS?
Could you please provide some information on the policies and the event handler?
It looks like you have a passthru policy and some token-event-handler?

**Comment by p53** [comment]
sorry yes we have eventhandler for this
yes we are creating token from userstore phone number
we don't have anything set as multivalue attribute but as i it is in docs mobile should be multivalue attribute by default

```
    state: present
    action: "enroll"
    active: "true"
    condition: ""
    conditions:
        realm: "somedomain.com"
        result_value: "True"
        user_token_number: "0"
    event: "validate_check"
    handlermodule: "Token"
    ordering: "0"
    option.realm: "somedomain.com"
    option.tokentype: "sms"
    option.user: "true"
```

```
  - name: some_authentication
    state: present
    action:
      - otppin=userstore
      - reset_all_user_tokens=true
      - passthru=userstore
      - challenge_response=totp
    scope: authentication
    realm:
      - somedomain.com
    resolver:
      - ldap_resolver
    user: ''
    active: 'true'
    check_all_resolvers: 'false'
    client: ''
    time: ''
    adminrealm: []
    priority: 2
```

```
    type: ldapresolver
    BINDDN: "some_dn"
    AUTHTYPE: "Simple"
    LDAPBASE: "somebase"
    LDAPURI: "ldaps://somedomain.com"
    EDITABLE: "false"
    LDAPSEARCHFILTER: "(uid=*)(objectClass=inetOrgPerson)"
    UIDTYPE: "DN"
    BINDPW: "somepass"
    USERINFO: "{ "mobile" : "mobile","email" : "mail","surname" : "sn","givenname" : "givenName" }"
    TIMEOUT: "5"
    SIZELIMIT: "500"
    SCOPE: "SUBTREE"
    NOREFERRALS: "false"
    LOGINNAMEATTRIBUTE: "uid"
```
