### ISSUE TITLE
Some clickable elements in the UI don't change the cursor

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#1725]
Some `a` elements (anchor`) which do not contain an `href`-attribute don't appear as clickable (by means of changing the cursor symbol) in the UI due to the fact that they only call some JS with the onClick event.
This can be fixed very quick with a small CSS entry:
```css
a:not([href]) {
    cursor: pointer;
}
```
