### ISSUE TITLE
Policy rule does not apply if tokenowner.realm_id != tokenrealm.realm_id

### ISSUE THREAD

**Issue by katgirl** [privacyidea/privacyidea#3253]
### Top-level intent

If a policy exception is made for an IP address and a realm, then it will be skipped if the assigned realm is different from the tokenrealm. This only happens if there is no other token already with the user.

### Steps to reproduce

Assumption:
  - two realms (default and default-rollout)
  - new tokens are assigned to users in default-rollout and the token realm is then changed to default in a self-service (activation)

1. create two policies
```
      authentication_otp:
        Scope: authentication
        action: otppin = none
        priority: 11
        client: <IP>
        user realm: default
      authentication_default:
        Scope: authentication
        action: otppin = userstore
        priority: 19
```
2. roll out user token in default-rollout
3. move token into realm default

Rule authentication_otp does not apply to /validate/check.

4. user rolls out himself a token in default or a token in default is rolled out for the user.

Rule authentication_otp applies to both tokens.

### Expected outcome

Either the rule really only applies to tokenowner.realm_id or to tokenrealm.realm_id, but not in mixed operation, which makes support opaque and is disastrous from a security point of view.

We have had the following case so far:
Login with username + password -> and token for confirmation which was still in default-rollout.

If we assign default-rollout as a rule, it always works, but as described above it is unattractive, because the user has never activated this token from our point of view and therefore does not accept the operations.

### Actual outcome

What did actually happen?

### Configuration

* **privacyIDEA version**: 3.6.2 / 3.7.1
* **Installation method**: PyPI
