### ISSUE TITLE
Menu not loaded in docker deployment

### ISSUE THREAD

**Issue by invizus** [privacyidea/privacyidea#3496]
### Top-level intent

Run privacyidea in docker, login and configure my local experimental installation. Menus do not load for some reason, no obvious logs in browser console or log files.

As this is not currently supported method of deployment I am at least hoping for advice how to debug, where to start.

### Steps to reproduce
I am aware that currently the recommended method to install privacyidea is in virtualenv. But I would like to run it in a docker container and I am experimenting with below. This also runs as root in the docker, because experimental.

#### 1. Prepare

`Dockerfile`
```
FROM python:3.8-bullseye
WORKDIR /app
COPY requirements.txt /app
RUN pip install -r https://raw.githubusercontent.com/privacyidea/privacyidea/v3.8/requirements.txt
RUN pip install -r requirements.txt
COPY pi.cfg /app
COPY app.py /app
COPY privacyidea.ini /app
COPY src/* /app/ # your other content like cert/keys, encfile, etc.
EXPOSE 8080
CMD uwsgi --ini /app/privacyidea.ini
```
`requirements.txt` this installs latest 3.8 version
```
uwsgi
privacyIDEA==3.8
markupsafe==2.0.1
```
`privacyidea.ini`
```
[uwsgi]
processes = 2
master = true
vacuum = true
http = 0.0.0.0:8080
wsgi-file = app.py
```
`app.py`
```
import sys
sys.stdout = sys.stderr
from privacyidea.app import create_app
# Now we can select the config file:
application = create_app(config_name="production",
              config_file="/app/pi.cfg")
```
#### 2. build and run
run `docker build . -t privacyideadev`
`docker-compose.yml` :
```
version: "3.7"
services:
  pi:
    image: privacyideadev
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PRIVACYIDEA_CONFIGFILE=/app/pi.cfg
  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - /home/user/srv/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: *******
      MYSQL_DATABASE: *******
      MYSQL_USER: *******
      MYSQL_PASSWORD: *******
```
then run `docker-compose up` to run stack, get container ID or names: `docker ps`

run commands in docker
`docker exec -ti <containerid> pi-manage`

### Expected outcome
fully working app

### Actual outcome
Menu's do not load

![Screenshot from 2023-01-27 14-11-56](https://user-images.githubusercontent.com/12719400/215109199-876adaf0-a899-41fe-903a-ab675bf9a985.png)

![Screenshot from 2023-01-27 14-12-13](https://user-images.githubusercontent.com/12719400/215109211-d1fba4d4-79b0-4685-a6dd-e41a27b86577.png)

### Configuration

* **privacyIDEA version**: 3.8
* **Installation method**: experimental docker, uwsgi
* **Python version**: 3.8
* **Operating system**: bullseye
* **Webserver**: uwsgi
* **Token database**: MariaDB

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**
no errors, too many logs lines (600+) not sure which ones are relevant.
